version: '2'
services:
  web:
    build: .
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - dynamodb
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]