# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/base-service
    docker:
      # specify the version you desire here
      - image: karthikiyengar/node-nightwatch:0.0.2
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache
      - run:
          name: Install Serverless CLI
          command: sudo yarn global add serverless
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Install Serverless dynamodb local
          command: sls dynamodb install
      - run:
          name: Run local server with tests
          command: yarn start:test
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
  deploy:
    working_directory: ~/base-service
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache
      - run:
          name: Install Serverless CLI
          command: sudo yarn global add serverless
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Deploy to dev
          command: yarn deploy
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
  deploy-staging:
    working_directory: ~/base-service
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache
      - run:
          name: Install Serverless CLI
          command: sudo yarn global add serverless
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Deploy to stage
          command: yarn deploy:staging
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
  deploy-prod:
    working_directory: ~/base-service
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache
      - run:
          name: Install Serverless CLI
          command: sudo yarn global add serverless
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Deploy to production
          command: yarn deploy:production
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: production