export const CONTENT_TYPE_KEY = 'Content-Type';
export const CONTENT_TYPE_VALUE = 'application/json';
export const COCKTAIL_API_LIST_INGREDIENTS_URL = 'https://the-cocktail-db.p.rapidapi.com/list.php?i=list';
export const COCKTAIL_API_FETCH_BY_INGREDIENT_URL = 'https://the-cocktail-db.p.rapidapi.com/filter.php';
export const COCKTAIL_API_INGREDIENT_PARAM_NAME = 'i';
export const COCKTAIL_HEADERS_KEY_HOST = 'x-rapidapi-host';
export const COCKTAIL_HEADERS_VALUE_HOST = 'the-cocktail-db.p.rapidapi.com';
export const COCKTAIL_HEADERS_KEY_API_KEY = 'x-rapidapi-key';
export const COCKTAIL_HEADERS_VALUE_API_KEY = '804039b4f3msh8e0393b02761e2ap194e79jsn85758a297978';
